package de.gematik.ws.conn.cardservice.wsdl.v8_1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.3.6
 * 2020-05-02T19:08:10.027+02:00
 * Generated source version: 3.3.6
 *
 */
@WebService(targetNamespace = "http://ws.gematik.de/conn/CardService/WSDL/v8.1", name = "CardServicePortType")
@XmlSeeAlso({de.gematik.ws.conn.cardservice.v8.ObjectFactory.class, de.gematik.ws.conn.cardservicecommon.v2.ObjectFactory.class, oasis.names.tc.dss._1_0.core.schema.ObjectFactory.class, org.w3._2000._09.xmldsig_.ObjectFactory.class, de.gematik.ws.tel.error.v2.ObjectFactory.class, de.gematik.ws.conn.connectorcontext.v2.ObjectFactory.class, de.gematik.ws._int.version.productinformation.v1.ObjectFactory.class, de.gematik.ws.conn.connectorcommon.v5.ObjectFactory.class, oasis.names.tc.saml._1_0.assertion.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface CardServicePortType {

    @WebMethod(operationName = "VerifyPin", action = "http://ws.gematik.de/conn/CardService/v8.1#VerifyPin")
    @WebResult(name = "VerifyPinResponse", targetNamespace = "http://ws.gematik.de/conn/CardService/v8.1", partName = "parameter")
    public de.gematik.ws.conn.cardservicecommon.v2.PinResponseType verifyPin(

        @WebParam(partName = "parameter", name = "VerifyPin", targetNamespace = "http://ws.gematik.de/conn/CardService/v8.1")
        de.gematik.ws.conn.cardservice.v8.VerifyPin parameter
    ) throws FaultMessage;

    @WebMethod(operationName = "GetPinStatus", action = "http://ws.gematik.de/conn/CardService/v8.1#GetPinStatus")
    @WebResult(name = "GetPinStatusResponse", targetNamespace = "http://ws.gematik.de/conn/CardService/v8.1", partName = "parameter")
    public de.gematik.ws.conn.cardservice.v8.GetPinStatusResponse getPinStatus(

        @WebParam(partName = "parameter", name = "GetPinStatus", targetNamespace = "http://ws.gematik.de/conn/CardService/v8.1")
        de.gematik.ws.conn.cardservice.v8.GetPinStatus parameter
    ) throws FaultMessage;

    @WebMethod(operationName = "ChangePin", action = "http://ws.gematik.de/conn/CardService/v8.1#ChangePin")
    @WebResult(name = "ChangePinResponse", targetNamespace = "http://ws.gematik.de/conn/CardService/v8.1", partName = "parameter")
    public de.gematik.ws.conn.cardservicecommon.v2.PinResponseType changePin(

        @WebParam(partName = "parameter", name = "ChangePin", targetNamespace = "http://ws.gematik.de/conn/CardService/v8.1")
        de.gematik.ws.conn.cardservice.v8.ChangePin parameter
    ) throws FaultMessage;

    @WebMethod(operationName = "EnablePin", action = "http://ws.gematik.de/conn/CardService/v8.1#EnablePin")
    @WebResult(name = "EnablePinResponse", targetNamespace = "http://ws.gematik.de/conn/CardService/v8.1", partName = "parameter")
    public de.gematik.ws.conn.cardservicecommon.v2.PinResponseType enablePin(

        @WebParam(partName = "parameter", name = "EnablePin", targetNamespace = "http://ws.gematik.de/conn/CardService/v8.1")
        de.gematik.ws.conn.cardservice.v8.EnablePin parameter
    ) throws FaultMessage;

    @WebMethod(operationName = "DisablePin", action = "http://ws.gematik.de/conn/CardService/v8.1#DisablePin")
    @WebResult(name = "DisablePinResponse", targetNamespace = "http://ws.gematik.de/conn/CardService/v8.1", partName = "parameter")
    public de.gematik.ws.conn.cardservicecommon.v2.PinResponseType disablePin(

        @WebParam(partName = "parameter", name = "DisablePin", targetNamespace = "http://ws.gematik.de/conn/CardService/v8.1")
        de.gematik.ws.conn.cardservice.v8.DisablePin parameter
    ) throws FaultMessage;

    @WebMethod(operationName = "UnblockPin", action = "http://ws.gematik.de/conn/CardService/v8.1#UnblockPin")
    @WebResult(name = "UnblockPinResponse", targetNamespace = "http://ws.gematik.de/conn/CardService/v8.1", partName = "parameter")
    public de.gematik.ws.conn.cardservicecommon.v2.PinResponseType unblockPin(

        @WebParam(partName = "parameter", name = "UnblockPin", targetNamespace = "http://ws.gematik.de/conn/CardService/v8.1")
        de.gematik.ws.conn.cardservice.v8.UnblockPin parameter
    ) throws FaultMessage;
}
