
package helper.servicedirectory.wsdl.v3_1;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.3.6
 * 2020-05-02T19:08:06.063+02:00
 * Generated source version: 3.3.6
 */

@WebFault(name = "Fault", targetNamespace = "helper/ServiceDirectory/v3.1")
public class FaultMessage extends Exception {

    private java.lang.Object fault;

    public FaultMessage() {
        super();
    }

    public FaultMessage(String message) {
        super(message);
    }

    public FaultMessage(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public FaultMessage(String message, java.lang.Object fault) {
        super(message);
        this.fault = fault;
    }

    public FaultMessage(String message, java.lang.Object fault, java.lang.Throwable cause) {
        super(message, cause);
        this.fault = fault;
    }

    public java.lang.Object getFaultInfo() {
        return this.fault;
    }
}
