package helper.servicedirectory.wsdl.v3_1;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.3.6
 * 2020-05-02T19:08:06.105+02:00
 * Generated source version: 3.3.6
 *
 */
@WebServiceClient(name = "ServiceDrectory",
                  wsdlLocation = "classpath:META-INF/wsdl/ServiceDirectory.helper.wsdl",
                  targetNamespace = "helper/ServiceDirectory/WSDL/v3.1")
public class ServiceDrectory extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("helper/ServiceDirectory/WSDL/v3.1", "ServiceDrectory");
    public final static QName ServiceDirectoryPort = new QName("helper/ServiceDirectory/WSDL/v3.1", "ServiceDirectoryPort");
    static {
        URL url = ServiceDrectory.class.getClassLoader().getResource("META-INF/wsdl/ServiceDirectory.helper.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(ServiceDrectory.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "classpath:META-INF/wsdl/ServiceDirectory.helper.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ServiceDrectory(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ServiceDrectory(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServiceDrectory() {
        super(WSDL_LOCATION, SERVICE);
    }

    public ServiceDrectory(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ServiceDrectory(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ServiceDrectory(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns ServiceDirectoryPortType
     */
    @WebEndpoint(name = "ServiceDirectoryPort")
    public ServiceDirectoryPortType getServiceDirectoryPort() {
        return super.getPort(ServiceDirectoryPort, ServiceDirectoryPortType.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServiceDirectoryPortType
     */
    @WebEndpoint(name = "ServiceDirectoryPort")
    public ServiceDirectoryPortType getServiceDirectoryPort(WebServiceFeature... features) {
        return super.getPort(ServiceDirectoryPort, ServiceDirectoryPortType.class, features);
    }

}
