package helper.servicedirectory.wsdl.v3_1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.3.6
 * 2020-05-02T19:08:06.095+02:00
 * Generated source version: 3.3.6
 *
 */
@WebService(targetNamespace = "helper/ServiceDirectory/WSDL/v3.1", name = "ServiceDirectoryPortType")
@XmlSeeAlso({de.gematik.ws.conn.serviceinformation.v2.ObjectFactory.class, de.gematik.ws.conn.servicedirectory.v3.ObjectFactory.class, helper.servicedirectory.v3.ObjectFactory.class, de.gematik.ws._int.version.productinformation.v1.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ServiceDirectoryPortType {

    @WebMethod(operationName = "GetConnectorServices", action = "helper/ServiceDirectory/v3.1#GetConnectorServices")
    @WebResult(name = "ConnectorServices", targetNamespace = "http://ws.gematik.de/conn/ServiceDirectory/v3.1", partName = "parameter")
    public de.gematik.ws.conn.servicedirectory.v3.ConnectorServices getConnectorServices(

        @WebParam(partName = "parameter", name = "ServiceDirectoryRequest", targetNamespace = "helper/ServiceDirectory/v3.1")
        java.lang.Object parameter
    ) throws FaultMessage;
}
