package de.gematik.ws.conn.certificateservice.wsdl.v6_0;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.3.6
 * 2020-05-02T19:08:13.690+02:00
 * Generated source version: 3.3.6
 *
 */
@WebService(targetNamespace = "http://ws.gematik.de/conn/CertificateService/WSDL/v6.0", name = "CertificateServicePortType")
@XmlSeeAlso({de.gematik.ws.conn.certificateservicecommon.v2.ObjectFactory.class, oasis.names.tc.dss._1_0.core.schema.ObjectFactory.class, org.w3._2000._09.xmldsig_.ObjectFactory.class, de.gematik.ws.tel.error.v2.ObjectFactory.class, de.gematik.ws.conn.connectorcontext.v2.ObjectFactory.class, de.gematik.ws.conn.connectorcommon.v5.ObjectFactory.class, oasis.names.tc.saml._1_0.assertion.ObjectFactory.class, de.gematik.ws.conn.certificateservice.v6.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface CertificateServicePortType {

    @WebMethod(operationName = "CheckCertificateExpiration", action = "http://ws.gematik.de/conn/CertificateService/v6.0#CheckCertificateExpiration")
    @WebResult(name = "CheckCertificateExpirationResponse", targetNamespace = "http://ws.gematik.de/conn/CertificateService/v6.0", partName = "parameter")
    public de.gematik.ws.conn.certificateservice.v6.CheckCertificateExpirationResponse checkCertificateExpiration(

        @WebParam(partName = "parameter", name = "CheckCertificateExpiration", targetNamespace = "http://ws.gematik.de/conn/CertificateService/v6.0")
        de.gematik.ws.conn.certificateservice.v6.CheckCertificateExpiration parameter
    ) throws FaultMessage;

    @WebMethod(operationName = "ReadCardCertificate", action = "http://ws.gematik.de/conn/CertificateService/v6.0#ReadCardCertificate")
    @WebResult(name = "ReadCardCertificateResponse", targetNamespace = "http://ws.gematik.de/conn/CertificateService/v6.0", partName = "parameter")
    public de.gematik.ws.conn.certificateservice.v6.ReadCardCertificateResponse readCardCertificate(

        @WebParam(partName = "parameter", name = "ReadCardCertificate", targetNamespace = "http://ws.gematik.de/conn/CertificateService/v6.0")
        de.gematik.ws.conn.certificateservice.v6.ReadCardCertificate parameter
    ) throws FaultMessage;

    @WebMethod(operationName = "VerifyCertificate", action = "http://ws.gematik.de/conn/CertificateService/v6.0#VerifyCertificate")
    @WebResult(name = "VerifyCertificateResponse", targetNamespace = "http://ws.gematik.de/conn/CertificateService/v6.0", partName = "parameter")
    public de.gematik.ws.conn.certificateservice.v6.VerifyCertificateResponse verifyCertificate(

        @WebParam(partName = "parameter", name = "VerifyCertificate", targetNamespace = "http://ws.gematik.de/conn/CertificateService/v6.0")
        de.gematik.ws.conn.certificateservice.v6.VerifyCertificate parameter
    ) throws FaultMessage;
}
