package de.gematik.ws.conn.vsds.kvkservice.v4_0;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.3.6
 * 2020-05-02T19:08:26.826+02:00
 * Generated source version: 3.3.6
 *
 */
@WebService(targetNamespace = "http://ws.gematik.de/conn/vsds/KvkService/v4.0", name = "KVKServicePortType")
@XmlSeeAlso({oasis.names.tc.dss._1_0.core.schema.ObjectFactory.class, org.w3._2000._09.xmldsig_.ObjectFactory.class, de.gematik.ws.tel.error.v2.ObjectFactory.class, de.gematik.ws.conn.vsds.kvkservice.v4.ObjectFactory.class, de.gematik.ws.conn.connectorcontext.v2.ObjectFactory.class, de.gematik.ws.conn.connectorcommon.v5.ObjectFactory.class, oasis.names.tc.saml._1_0.assertion.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface KVKServicePortType {

    @WebMethod(operationName = "ReadKVK", action = "http://ws.gematik.de/conn/vsds/KvkService/v4.0#ReadVDT")
    @WebResult(name = "ReadKVKResponse", targetNamespace = "http://ws.gematik.de/conn/vsds/KvkService/v4.0", partName = "parameter")
    public de.gematik.ws.conn.vsds.kvkservice.v4.ReadKVKResponse readKVK(

        @WebParam(partName = "parameter", name = "ReadKVK", targetNamespace = "http://ws.gematik.de/conn/vsds/KvkService/v4.0")
        de.gematik.ws.conn.vsds.kvkservice.v4.ReadKVK parameter
    ) throws FaultMessage;
}
