package de.gematik.ws.conn.vsds.kvkservice.v4_0;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.3.6
 * 2020-05-02T19:08:26.839+02:00
 * Generated source version: 3.3.6
 *
 */
@WebServiceClient(name = "KVKService",
                  wsdlLocation = "classpath:META-INF/wsdl/api-telematik/conn/vsds/KvkService.wsdl",
                  targetNamespace = "http://ws.gematik.de/conn/vsds/KvkService/v4.0")
public class KVKService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://ws.gematik.de/conn/vsds/KvkService/v4.0", "KVKService");
    public final static QName KVKServicePort = new QName("http://ws.gematik.de/conn/vsds/KvkService/v4.0", "KVKServicePort");
    static {
        URL url = KVKService.class.getClassLoader().getResource("META-INF/wsdl/api-telematik/conn/vsds/KvkService.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(KVKService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "classpath:META-INF/wsdl/api-telematik/conn/vsds/KvkService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public KVKService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public KVKService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public KVKService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public KVKService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public KVKService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public KVKService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns KVKServicePortType
     */
    @WebEndpoint(name = "KVKServicePort")
    public KVKServicePortType getKVKServicePort() {
        return super.getPort(KVKServicePort, KVKServicePortType.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns KVKServicePortType
     */
    @WebEndpoint(name = "KVKServicePort")
    public KVKServicePortType getKVKServicePort(WebServiceFeature... features) {
        return super.getPort(KVKServicePort, KVKServicePortType.class, features);
    }

}
