package de.gematik.ws.conn.vsds.vsdservice.v5_2;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.3.6
 * 2020-05-02T19:08:28.521+02:00
 * Generated source version: 3.3.6
 *
 */
@WebService(targetNamespace = "http://ws.gematik.de/conn/vsds/VSDService/v5.2", name = "VSDServicePortType")
@XmlSeeAlso({oasis.names.tc.dss._1_0.core.schema.ObjectFactory.class, org.w3._2000._09.xmldsig_.ObjectFactory.class, de.gematik.ws.tel.error.v2.ObjectFactory.class, de.gematik.ws.conn.connectorcontext.v2.ObjectFactory.class, de.gematik.ws.conn.vsds.vsdservice.v5.ObjectFactory.class, de.gematik.ws.conn.connectorcommon.v5.ObjectFactory.class, oasis.names.tc.saml._1_0.assertion.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface VSDServicePortType {

    @WebMethod(operationName = "ReadVSD", action = "http://ws.gematik.de/conn/vsds/VSDService/v6.0#ReadVSD")
    @WebResult(name = "ReadVSDResponse", targetNamespace = "http://ws.gematik.de/conn/vsds/VSDService/v5.2", partName = "parameter")
    public de.gematik.ws.conn.vsds.vsdservice.v5.ReadVSDResponse readVSD(

        @WebParam(partName = "parameter", name = "ReadVSD", targetNamespace = "http://ws.gematik.de/conn/vsds/VSDService/v5.2")
        de.gematik.ws.conn.vsds.vsdservice.v5.ReadVSD parameter
    ) throws FaultMessage;
}
