package de.gematik.ws.conn.vsds.vsdservice.v5_2;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.3.6
 * 2020-05-02T19:08:28.533+02:00
 * Generated source version: 3.3.6
 *
 */
@WebServiceClient(name = "VSDService",
                  wsdlLocation = "classpath:META-INF/wsdl/api-telematik/conn/vsds/VSDService.wsdl",
                  targetNamespace = "http://ws.gematik.de/conn/vsds/VSDService/v5.2")
public class VSDService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://ws.gematik.de/conn/vsds/VSDService/v5.2", "VSDService");
    public final static QName VSDServicePort = new QName("http://ws.gematik.de/conn/vsds/VSDService/v5.2", "VSDServicePort");
    static {
        URL url = VSDService.class.getClassLoader().getResource("META-INF/wsdl/api-telematik/conn/vsds/VSDService.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(VSDService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "classpath:META-INF/wsdl/api-telematik/conn/vsds/VSDService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public VSDService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public VSDService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public VSDService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public VSDService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public VSDService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public VSDService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns VSDServicePortType
     */
    @WebEndpoint(name = "VSDServicePort")
    public VSDServicePortType getVSDServicePort() {
        return super.getPort(VSDServicePort, VSDServicePortType.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns VSDServicePortType
     */
    @WebEndpoint(name = "VSDServicePort")
    public VSDServicePortType getVSDServicePort(WebServiceFeature... features) {
        return super.getPort(VSDServicePort, VSDServicePortType.class, features);
    }

}
