package de.gematik.ws.conn.amts.amtsservice.v1_0;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.3.6
 * 2020-05-02T19:08:20.950+02:00
 * Generated source version: 3.3.6
 *
 */
@WebService(targetNamespace = "http://ws.gematik.de/conn/amts/AMTSService/v1.0", name = "AMTSServicePortType")
@XmlSeeAlso({de.gematik.ws.conn.cardservicecommon.v2.ObjectFactory.class, oasis.names.tc.dss._1_0.core.schema.ObjectFactory.class, org.w3._2000._09.xmldsig_.ObjectFactory.class, de.gematik.ws.conn.amts.amtsservice.v1.ObjectFactory.class, de.gematik.ws.tel.error.v2.ObjectFactory.class, de.gematik.ws.conn.connectorcontext.v2.ObjectFactory.class, de.gematik.ws.conn.connectorcommon.v5.ObjectFactory.class, oasis.names.tc.saml._1_0.assertion.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface AMTSServicePortType {

    @WebMethod(operationName = "WriteMP", action = "http://ws.gematik.de/conn/amtss/AMTSService/WSDL/v1.0#WriteMP")
    @WebResult(name = "WriteMPResponse", targetNamespace = "http://ws.gematik.de/conn/amts/AMTSService/v1.0", partName = "parameter")
    public de.gematik.ws.conn.amts.amtsservice.v1.WriteMPResponse writeMP(

        @WebParam(partName = "parameter", name = "WriteMP", targetNamespace = "http://ws.gematik.de/conn/amts/AMTSService/v1.0")
        de.gematik.ws.conn.amts.amtsservice.v1.WriteMP parameter
    ) throws FaultMessage;

    @WebMethod(operationName = "DeleteConsent", action = "http://ws.gematik.de/conn/amtss/AMTSService/WSDL/v1.0#DeleteConsent")
    @WebResult(name = "DeleteConsentResponse", targetNamespace = "http://ws.gematik.de/conn/amts/AMTSService/v1.0", partName = "parameter")
    public de.gematik.ws.conn.amts.amtsservice.v1.DeleteConsentResponse deleteConsent(

        @WebParam(partName = "parameter", name = "DeleteConsent", targetNamespace = "http://ws.gematik.de/conn/amts/AMTSService/v1.0")
        de.gematik.ws.conn.amts.amtsservice.v1.DeleteConsent parameter
    ) throws FaultMessage;

    @WebMethod(operationName = "WriteConsent", action = "http://ws.gematik.de/conn/amtss/AMTSService/WSDL/v1.0#WriteConsent")
    @WebResult(name = "WriteConsentResponse", targetNamespace = "http://ws.gematik.de/conn/amts/AMTSService/v1.0", partName = "parameter")
    public de.gematik.ws.conn.amts.amtsservice.v1.WriteConsentResponse writeConsent(

        @WebParam(partName = "parameter", name = "WriteConsent", targetNamespace = "http://ws.gematik.de/conn/amts/AMTSService/v1.0")
        de.gematik.ws.conn.amts.amtsservice.v1.WriteConsent parameter
    ) throws FaultMessage;

    @WebMethod(operationName = "ReadMP", action = "http://ws.gematik.de/conn/amtss/AMTSService/WSDL/v1.0#ReadMP")
    @WebResult(name = "ReadMPResponse", targetNamespace = "http://ws.gematik.de/conn/amts/AMTSService/v1.0", partName = "parameter")
    public de.gematik.ws.conn.amts.amtsservice.v1.ReadMPResponse readMP(

        @WebParam(partName = "parameter", name = "ReadMP", targetNamespace = "http://ws.gematik.de/conn/amts/AMTSService/v1.0")
        de.gematik.ws.conn.amts.amtsservice.v1.ReadMP parameter
    ) throws FaultMessage;

    @WebMethod(operationName = "ReadConsent", action = "http://ws.gematik.de/conn/amtss/AMTSService/WSDL/v1.0#ReadConsent")
    @WebResult(name = "ReadConsentResponse", targetNamespace = "http://ws.gematik.de/conn/amts/AMTSService/v1.0", partName = "parameter")
    public de.gematik.ws.conn.amts.amtsservice.v1.ReadConsentResponse readConsent(

        @WebParam(partName = "parameter", name = "ReadConsent", targetNamespace = "http://ws.gematik.de/conn/amts/AMTSService/v1.0")
        de.gematik.ws.conn.amts.amtsservice.v1.ReadConsent parameter
    ) throws FaultMessage;
}
