package de.gematik.ws.conn.amts.amtsservice.v1_0;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.3.6
 * 2020-05-02T19:08:20.964+02:00
 * Generated source version: 3.3.6
 *
 */
@WebServiceClient(name = "AMTSService",
                  wsdlLocation = "classpath:META-INF/wsdl/api-telematik/conn/amtss/AMTSService.wsdl",
                  targetNamespace = "http://ws.gematik.de/conn/amts/AMTSService/v1.0")
public class AMTSService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://ws.gematik.de/conn/amts/AMTSService/v1.0", "AMTSService");
    public final static QName AMTSServicePort = new QName("http://ws.gematik.de/conn/amts/AMTSService/v1.0", "AMTSServicePort");
    static {
        URL url = AMTSService.class.getClassLoader().getResource("META-INF/wsdl/api-telematik/conn/amtss/AMTSService.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(AMTSService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "classpath:META-INF/wsdl/api-telematik/conn/amtss/AMTSService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public AMTSService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public AMTSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AMTSService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public AMTSService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public AMTSService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public AMTSService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns AMTSServicePortType
     */
    @WebEndpoint(name = "AMTSServicePort")
    public AMTSServicePortType getAMTSServicePort() {
        return super.getPort(AMTSServicePort, AMTSServicePortType.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AMTSServicePortType
     */
    @WebEndpoint(name = "AMTSServicePort")
    public AMTSServicePortType getAMTSServicePort(WebServiceFeature... features) {
        return super.getPort(AMTSServicePort, AMTSServicePortType.class, features);
    }

}
