package de.gematik.ws.conn.encryptionservice.wsdl.v6_1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.3.6
 * 2020-05-02T19:08:15.372+02:00
 * Generated source version: 3.3.6
 *
 */
@WebService(targetNamespace = "http://ws.gematik.de/conn/EncryptionService/WSDL/v6.1", name = "EncryptionServicePortType")
@XmlSeeAlso({oasis.names.tc.dss._1_0.core.schema.ObjectFactory.class, org.w3._2000._09.xmldsig_.ObjectFactory.class, de.gematik.ws.tel.error.v2.ObjectFactory.class, de.gematik.ws.conn.connectorcontext.v2.ObjectFactory.class, de.gematik.ws.conn.encryptionservice.v6.ObjectFactory.class, de.gematik.ws.conn.connectorcommon.v5.ObjectFactory.class, oasis.names.tc.saml._1_0.assertion.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface EncryptionServicePortType {

    @WebMethod(operationName = "DecryptDocument", action = "http://ws.gematik.de/conn/crypt/EncryptionService/v6.1#DecryptDocument")
    @WebResult(name = "DecryptDocumentResponse", targetNamespace = "http://ws.gematik.de/conn/EncryptionService/v6.1", partName = "parameter")
    public de.gematik.ws.conn.encryptionservice.v6.DecryptDocumentResponse decryptDocument(

        @WebParam(partName = "parameter", name = "DecryptDocument", targetNamespace = "http://ws.gematik.de/conn/EncryptionService/v6.1")
        de.gematik.ws.conn.encryptionservice.v6.DecryptDocument parameter
    ) throws FaultMessage;

    @WebMethod(operationName = "EncryptDocument", action = "http://ws.gematik.de/conn/EncryptionService/v6.1#EncryptDocument")
    @WebResult(name = "EncryptDocumentResponse", targetNamespace = "http://ws.gematik.de/conn/EncryptionService/v6.1", partName = "parameter")
    public de.gematik.ws.conn.encryptionservice.v6.EncryptDocumentResponse encryptDocument(

        @WebParam(partName = "parameter", name = "EncryptDocument", targetNamespace = "http://ws.gematik.de/conn/EncryptionService/v6.1")
        de.gematik.ws.conn.encryptionservice.v6.EncryptDocument parameter
    ) throws FaultMessage;
}
