package de.gematik.ws.conn.nfds.nfdservice.wsdl.v1_0;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.3.6
 * 2020-05-02T19:08:25.100+02:00
 * Generated source version: 3.3.6
 *
 */
@WebService(targetNamespace = "http://ws.gematik.de/conn/nfds/NFDService/WSDL/v1.0", name = "NFDServicePortType")
@XmlSeeAlso({de.gematik.ws.conn.certificateservicecommon.v2.ObjectFactory.class, org.w3._2001._04.xmlenc_.ObjectFactory.class, de.gematik.ws.conn.connectorcontext.v2.ObjectFactory.class, org.etsi.uri._01903.v1_3.ObjectFactory.class, de.gematik.ws.conn.signatureservice.v7.ObjectFactory.class, oasis.names.tc.dss_x._1_0.profiles.verificationreport.schema_.ObjectFactory.class, de.gematik.ws.conn.connectorcommon.v5.ObjectFactory.class, org.etsi.uri._02231.v2_.ObjectFactory.class, de.gematik.ws.conn.nfds.nfdservice.v1.ObjectFactory.class, oasis.names.tc.dss._1_0.core.schema.ObjectFactory.class, org.w3._2000._09.xmldsig_.ObjectFactory.class, de.gematik.ws.tel.error.v2.ObjectFactory.class, oasis.names.tc.dss_x._1_0.profiles.signaturepolicy.schema_.ObjectFactory.class, oasis.names.tc.saml._2_0.assertion.ObjectFactory.class, oasis.names.tc.saml._1_0.assertion.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface NFDServicePortType {

    @WebMethod(operationName = "EraseNFD", action = "http://ws.gematik.de/conn/nfds/NFDService/WSDL/v1.0#EraseNFD")
    @WebResult(name = "EraseNFDResponse", targetNamespace = "http://ws.gematik.de/conn/nfds/NFDService/v1.0", partName = "parameters")
    public de.gematik.ws.conn.nfds.nfdservice.v1.EraseNFDResponse eraseNFD(

        @WebParam(partName = "parameters", name = "EraseNFD", targetNamespace = "http://ws.gematik.de/conn/nfds/NFDService/v1.0")
        de.gematik.ws.conn.nfds.nfdservice.v1.EraseNFD parameters
    ) throws FaultMessage;

    @WebMethod(operationName = "WriteNFD", action = "http://ws.gematik.de/conn/nfds/NFDService/WSDL/v1.0#WriteNFD")
    @WebResult(name = "WriteNFDResponse", targetNamespace = "http://ws.gematik.de/conn/nfds/NFDService/v1.0", partName = "parameters")
    public de.gematik.ws.conn.nfds.nfdservice.v1.WriteNFDResponse writeNFD(

        @WebParam(partName = "parameters", name = "WriteNFD", targetNamespace = "http://ws.gematik.de/conn/nfds/NFDService/v1.0")
        de.gematik.ws.conn.nfds.nfdservice.v1.WriteNFD parameters
    ) throws FaultMessage;

    @WebMethod(operationName = "ReadNFD", action = "http://ws.gematik.de/conn/nfds/NFDService/WSDL/v1.0#ReadNFD")
    @WebResult(name = "ReadNFDResponse", targetNamespace = "http://ws.gematik.de/conn/nfds/NFDService/v1.0", partName = "parameters")
    public de.gematik.ws.conn.nfds.nfdservice.v1.ReadNFDResponse readNFD(

        @WebParam(partName = "parameter", name = "ReadNFD", targetNamespace = "http://ws.gematik.de/conn/nfds/NFDService/v1.0")
        de.gematik.ws.conn.nfds.nfdservice.v1.ReadNFD parameter
    ) throws FaultMessage;
}
