package de.gematik.ws.conn.nfds.nfdservice.wsdl.v1_0;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.3.6
 * 2020-05-02T19:08:25.114+02:00
 * Generated source version: 3.3.6
 *
 */
@WebServiceClient(name = "NFDService",
                  wsdlLocation = "classpath:META-INF/wsdl/api-telematik/conn/nfds/NFDService.wsdl",
                  targetNamespace = "http://ws.gematik.de/conn/nfds/NFDService/WSDL/v1.0")
public class NFDService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://ws.gematik.de/conn/nfds/NFDService/WSDL/v1.0", "NFDService");
    public final static QName NFDServicePort = new QName("http://ws.gematik.de/conn/nfds/NFDService/WSDL/v1.0", "NFDServicePort");
    static {
        URL url = NFDService.class.getClassLoader().getResource("META-INF/wsdl/api-telematik/conn/nfds/NFDService.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(NFDService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "classpath:META-INF/wsdl/api-telematik/conn/nfds/NFDService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public NFDService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public NFDService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public NFDService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public NFDService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public NFDService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public NFDService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns NFDServicePortType
     */
    @WebEndpoint(name = "NFDServicePort")
    public NFDServicePortType getNFDServicePort() {
        return super.getPort(NFDServicePort, NFDServicePortType.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns NFDServicePortType
     */
    @WebEndpoint(name = "NFDServicePort")
    public NFDServicePortType getNFDServicePort(WebServiceFeature... features) {
        return super.getPort(NFDServicePort, NFDServicePortType.class, features);
    }

}
