package de.gematik.ws.conn.eventservice.wsdl.v7_2;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.3.6
 * 2020-05-02T19:08:17.179+02:00
 * Generated source version: 3.3.6
 *
 */
@WebServiceClient(name = "EventService",
                  wsdlLocation = "classpath:META-INF/wsdl/api-telematik/conn/EventService.wsdl",
                  targetNamespace = "http://ws.gematik.de/conn/EventService/WSDL/v7.2")
public class EventService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://ws.gematik.de/conn/EventService/WSDL/v7.2", "EventService");
    public final static QName EventServicePort = new QName("http://ws.gematik.de/conn/EventService/WSDL/v7.2", "EventServicePort");
    static {
        URL url = EventService.class.getClassLoader().getResource("META-INF/wsdl/api-telematik/conn/EventService.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(EventService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "classpath:META-INF/wsdl/api-telematik/conn/EventService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public EventService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public EventService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EventService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public EventService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public EventService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public EventService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns EventServicePortType
     */
    @WebEndpoint(name = "EventServicePort")
    public EventServicePortType getEventServicePort() {
        return super.getPort(EventServicePort, EventServicePortType.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EventServicePortType
     */
    @WebEndpoint(name = "EventServicePort")
    public EventServicePortType getEventServicePort(WebServiceFeature... features) {
        return super.getPort(EventServicePort, EventServicePortType.class, features);
    }

}
