package de.gematik.ws.conn.eventservice.wsdl.v7_2;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.3.6
 * 2020-05-02T19:08:17.162+02:00
 * Generated source version: 3.3.6
 *
 */
@WebService(targetNamespace = "http://ws.gematik.de/conn/EventService/WSDL/v7.2", name = "EventServicePortType")
@XmlSeeAlso({de.gematik.ws.conn.cardservice.v8.ObjectFactory.class, de.gematik.ws.conn.cardservicecommon.v2.ObjectFactory.class, oasis.names.tc.dss._1_0.core.schema.ObjectFactory.class, org.w3._2000._09.xmldsig_.ObjectFactory.class, de.gematik.ws.tel.error.v2.ObjectFactory.class, de.gematik.ws.conn.cardterminalinfo.v8.ObjectFactory.class, de.gematik.ws.conn.connectorcontext.v2.ObjectFactory.class, de.gematik.ws._int.version.productinformation.v1.ObjectFactory.class, de.gematik.ws.conn.eventservice.v7.ObjectFactory.class, de.gematik.ws.conn.connectorcommon.v5.ObjectFactory.class, oasis.names.tc.saml._1_0.assertion.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface EventServicePortType {

    @WebMethod(operationName = "Subscribe", action = "http://ws.gematik.de/conn/EventService/v7.2#Subscribe")
    @WebResult(name = "SubscribeResponse", targetNamespace = "http://ws.gematik.de/conn/EventService/v7.2", partName = "parameter")
    public de.gematik.ws.conn.eventservice.v7.SubscribeResponse subscribe(

        @WebParam(partName = "parameter", name = "Subscribe", targetNamespace = "http://ws.gematik.de/conn/EventService/v7.2")
        de.gematik.ws.conn.eventservice.v7.Subscribe parameter
    ) throws FaultMessage;

    @WebMethod(operationName = "GetResourceInformation", action = "http://ws.gematik.de/conn/EventService/v7.2#GetResourceInformation")
    @WebResult(name = "GetResourceInformationResponse", targetNamespace = "http://ws.gematik.de/conn/EventService/v7.2", partName = "parameter")
    public de.gematik.ws.conn.eventservice.v7.GetResourceInformationResponse getResourceInformation(

        @WebParam(partName = "parameter", name = "GetResourceInformation", targetNamespace = "http://ws.gematik.de/conn/EventService/v7.2")
        de.gematik.ws.conn.eventservice.v7.GetResourceInformation parameter
    ) throws FaultMessage;

    @WebMethod(operationName = "GetSubscription", action = "http://ws.gematik.de/conn/EventService/v7.2#GetSubscription")
    @WebResult(name = "GetSubscriptionResponse", targetNamespace = "http://ws.gematik.de/conn/EventService/v7.2", partName = "parameter")
    public de.gematik.ws.conn.eventservice.v7.GetSubscriptionResponse getSubscription(

        @WebParam(partName = "parameter", name = "GetSubscription", targetNamespace = "http://ws.gematik.de/conn/EventService/v7.2")
        de.gematik.ws.conn.eventservice.v7.GetSubscription parameter
    ) throws FaultMessage;

    @WebMethod(operationName = "Unsubscribe", action = "http://ws.gematik.de/conn/EventService/v7.2#Unsubscribe")
    @WebResult(name = "UnsubscribeResponse", targetNamespace = "http://ws.gematik.de/conn/EventService/v7.2", partName = "parameter")
    public de.gematik.ws.conn.eventservice.v7.UnsubscribeResponse unsubscribe(

        @WebParam(partName = "parameter", name = "Unsubscribe", targetNamespace = "http://ws.gematik.de/conn/EventService/v7.2")
        de.gematik.ws.conn.eventservice.v7.Unsubscribe parameter
    ) throws FaultMessage;

    @WebMethod(operationName = "GetCardTerminals", action = "http://ws.gematik.de/conn/EventService/v7.2#GetCardTerminals")
    @WebResult(name = "GetCardTerminalsResponse", targetNamespace = "http://ws.gematik.de/conn/EventService/v7.2", partName = "parameter")
    public de.gematik.ws.conn.eventservice.v7.GetCardTerminalsResponse getCardTerminals(

        @WebParam(partName = "parameter", name = "GetCardTerminals", targetNamespace = "http://ws.gematik.de/conn/EventService/v7.2")
        de.gematik.ws.conn.eventservice.v7.GetCardTerminals parameter
    ) throws FaultMessage;

    @WebMethod(operationName = "RenewSubscriptions", action = "http://ws.gematik.de/conn/EventService/v7.2#RenewSubscriptions")
    @WebResult(name = "RenewSubscriptionsResponse", targetNamespace = "http://ws.gematik.de/conn/EventService/v7.2", partName = "parameter")
    public de.gematik.ws.conn.eventservice.v7.RenewSubscriptionsResponse renewSubscriptions(

        @WebParam(partName = "parameter", name = "RenewSubscriptions", targetNamespace = "http://ws.gematik.de/conn/EventService/v7.2")
        de.gematik.ws.conn.eventservice.v7.RenewSubscriptions parameter
    ) throws FaultMessage;

    @WebMethod(operationName = "GetCards", action = "http://ws.gematik.de/conn/EventService/v7.2#GetCards")
    @WebResult(name = "GetCardsResponse", targetNamespace = "http://ws.gematik.de/conn/EventService/v7.2", partName = "parameter")
    public de.gematik.ws.conn.eventservice.v7.GetCardsResponse getCards(

        @WebParam(partName = "parameter", name = "GetCards", targetNamespace = "http://ws.gematik.de/conn/EventService/v7.2")
        de.gematik.ws.conn.eventservice.v7.GetCards parameter
    ) throws FaultMessage;
}
