package de.gematik.ws.conn.nfds.dpeservice.wsdl.v1_0;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.3.6
 * 2020-05-02T19:08:22.823+02:00
 * Generated source version: 3.3.6
 *
 */
@WebService(targetNamespace = "http://ws.gematik.de/conn/nfds/DPEService/WSDL/v1.0", name = "DPEServicePortType")
@XmlSeeAlso({oasis.names.tc.dss._1_0.core.schema.ObjectFactory.class, de.gematik.ws.conn.nfds.dpeservice.v1.ObjectFactory.class, org.w3._2000._09.xmldsig_.ObjectFactory.class, de.gematik.ws.tel.error.v2.ObjectFactory.class, de.gematik.ws.conn.connectorcontext.v2.ObjectFactory.class, de.gematik.ws.conn.connectorcommon.v5.ObjectFactory.class, oasis.names.tc.saml._1_0.assertion.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface DPEServicePortType {

    @WebMethod(operationName = "WriteDPE", action = "http://ws.gematik.de/conn/nfds/WSDL/DPEService/v1.0#WriteDPE")
    @WebResult(name = "WriteDPEResponse", targetNamespace = "http://ws.gematik.de/conn/nfds/DPEService/v1.0", partName = "parameters")
    public de.gematik.ws.conn.nfds.dpeservice.v1.WriteDPEResponse writeDPE(

        @WebParam(partName = "parameters", name = "WriteDPE", targetNamespace = "http://ws.gematik.de/conn/nfds/DPEService/v1.0")
        de.gematik.ws.conn.nfds.dpeservice.v1.WriteDPE parameters
    ) throws FaultMessage;

    @WebMethod(operationName = "EraseDPE", action = "http://ws.gematik.de/conn/nfds/WSDL/DPEService/v1.0#EraseDPE")
    @WebResult(name = "EraseDPEResponse", targetNamespace = "http://ws.gematik.de/conn/nfds/DPEService/v1.0", partName = "parameters")
    public de.gematik.ws.conn.nfds.dpeservice.v1.EraseDPEResponse eraseDPE(

        @WebParam(partName = "parameters", name = "EraseDPE", targetNamespace = "http://ws.gematik.de/conn/nfds/DPEService/v1.0")
        de.gematik.ws.conn.nfds.dpeservice.v1.EraseDPE parameters
    ) throws FaultMessage;

    @WebMethod(operationName = "ReadDPE", action = "http://ws.gematik.de/conn/nfds/WSDL/DPEService/v1.0#ReadDPE")
    @WebResult(name = "ReadDPEResponse", targetNamespace = "http://ws.gematik.de/conn/nfds/DPEService/v1.0", partName = "parameters")
    public de.gematik.ws.conn.nfds.dpeservice.v1.ReadDPEResponse readDPE(

        @WebParam(partName = "parameter", name = "ReadDPE", targetNamespace = "http://ws.gematik.de/conn/nfds/DPEService/v1.0")
        de.gematik.ws.conn.nfds.dpeservice.v1.ReadDPE parameter
    ) throws FaultMessage;
}
