package de.gematik.ws.conn.cardterminalservice.wsdl.v1_1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.3.6
 * 2020-05-02T19:08:11.986+02:00
 * Generated source version: 3.3.6
 *
 */
@WebService(targetNamespace = "http://ws.gematik.de/conn/CardTerminalService/WSDL/v1.1", name = "CardTerminalServicePortType")
@XmlSeeAlso({de.gematik.ws.conn.cardservice.v8.ObjectFactory.class, de.gematik.ws.conn.cardservicecommon.v2.ObjectFactory.class, oasis.names.tc.dss._1_0.core.schema.ObjectFactory.class, org.w3._2000._09.xmldsig_.ObjectFactory.class, de.gematik.ws.tel.error.v2.ObjectFactory.class, de.gematik.ws.conn.connectorcontext.v2.ObjectFactory.class, de.gematik.ws._int.version.productinformation.v1.ObjectFactory.class, de.gematik.ws.conn.cardterminalservice.v1.ObjectFactory.class, de.gematik.ws.conn.connectorcommon.v5.ObjectFactory.class, oasis.names.tc.saml._1_0.assertion.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface CardTerminalServicePortType {

    @WebMethod(operationName = "RequestCard", action = "http://ws.gematik.de/conn/CardTerminalService/v1.1#RequestCard")
    @WebResult(name = "RequestCardResponse", targetNamespace = "http://ws.gematik.de/conn/CardTerminalService/v1.1", partName = "parameter")
    public de.gematik.ws.conn.cardterminalservice.v1.RequestCardResponse requestCard(

        @WebParam(partName = "parameter", name = "RequestCard", targetNamespace = "http://ws.gematik.de/conn/CardTerminalService/v1.1")
        de.gematik.ws.conn.cardterminalservice.v1.RequestCard parameter
    ) throws FaultMessage;

    @WebMethod(operationName = "EjectCard", action = "http://ws.gematik.de/conn/CardTerminalService/v1.1#EjectCard")
    @WebResult(name = "EjectCardResponse", targetNamespace = "http://ws.gematik.de/conn/CardTerminalService/v1.1", partName = "parameter")
    public de.gematik.ws.conn.cardterminalservice.v1.EjectCardResponse ejectCard(

        @WebParam(partName = "parameter", name = "EjectCard", targetNamespace = "http://ws.gematik.de/conn/CardTerminalService/v1.1")
        de.gematik.ws.conn.cardterminalservice.v1.EjectCard parameter
    ) throws FaultMessage;
}
